# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_QT/ErrorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_window(object):
    def setupUi(self, error_window):
        error_window.setObjectName("error_window")
        error_window.resize(445, 192)
        self.centralwidget = QtWidgets.QWidget(error_window)
        self.centralwidget.setObjectName("centralwidget")
        self.error_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.error_text.setGeometry(QtCore.QRect(10, 10, 421, 111))
        self.error_text.setObjectName("error_text")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(10, 130, 421, 51))
        self.ok_button.setObjectName("ok_button")
        error_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(error_window)
        QtCore.QMetaObject.connectSlotsByName(error_window)
        
        self.ok_button.clicked.connect(self.close_window)
        
        self.window = error_window
        
    def close_window(self):
        self.window.close()

    def retranslateUi(self, error_window):
        _translate = QtCore.QCoreApplication.translate
        error_window.setWindowTitle(_translate("error_window", "Error !"))
        self.ok_button.setText(_translate("error_window", "OK !"))
        
    def set_text_error(self, message):
        _translate = QtCore.QCoreApplication.translate
        self.error_text.setText(_translate("error_window", message))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error_window = QtWidgets.QMainWindow()
    ui = Ui_error_window()
    ui.setupUi(error_window)
    error_window.show()
    sys.exit(app.exec_())
